import { createClient } from "@supabase/supabase-js";
import { generateSlug } from "../lib/utils";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY || "";

const supabase = createClient(supabaseUrl, supabaseServiceKey);

interface SeedJob {
  title_hindi: string;
  title_english: string;
  company_name: string;
  location_area: string;
  category: string;
  salary_min: number;
  salary_max: number;
  salary_text_hindi: string;
  description_hindi: string;
  qualification: string;
  experience: string;
  contact_number: string;
  job_type: string;
}

const sampleJobs: SeedJob[] = [
  {
    title_hindi: "Zomato डिलीवरी बॉय चाहिए",
    title_english: "Zomato Delivery Boy Required",
    company_name: "Zomato",
    location_area: "Gomti Nagar",
    category: "delivery",
    salary_min: 10000,
    salary_max: 18000,
    salary_text_hindi: "₹10,000 - ₹18,000 प्रति महीना",
    description_hindi: "Zomato में डिलीवरी बॉय चाहिए। अपना बाइक होना जरूरी है। रोजाना कैश और इंसेंटिव मिलते हैं। सुबह 10 बजे से रात 9 बजे तक शिफ्ट में काम करना होगा।",
    qualification: "10वीं पास, वैध ड्राइविंग लाइसेंस",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543210",
    job_type: "full-time",
  },
  {
    title_hindi: "डेटा एंट्री ऑपरेटर चाहिए",
    title_english: "Data Entry Operator Required",
    company_name: "Sharma Infotech",
    location_area: "Hazratganj",
    category: "data-entry",
    salary_min: 8000,
    salary_max: 12000,
    salary_text_hindi: "₹8,000 - ₹12,000 प्रति महीना",
    description_hindi: "हजरतगंज स्थित ऑफिस में डेटा एंट्री ऑपरेटर चाहिए। टाइपिंग स्पीड 25 WPM होनी चाहिए। कंप्यूटर का बेसिक ज्ञान आवश्यक है।",
    qualification: "12वीं पास, टाइपिंग ज्ञान",
    experience: "1 साल का अनुभव",
    contact_number: "9876543211",
    job_type: "full-time",
  },
  {
    title_hindi: "ड्राइवर चाहिए इंदिरा नगर",
    title_english: "Driver Required Indira Nagar",
    company_name: "Singh Transport",
    location_area: "Indira Nagar",
    category: "driver",
    salary_min: 12000,
    salary_max: 15000,
    salary_text_hindi: "₹12,000 - ₹15,000 प्रति महीना",
    description_hindi: "इंदिरा नगर में ड्राइवर चाहिए। छोटी गाड़ी चलाने का अनुभव होना चाहिए। लखनऊ और आसपास के इलाकों में ड्राइवरी करनी होगी।",
    qualification: "10वीं पास, वैध ड्राइविंग लाइसेंस",
    experience: "2 साल का अनुभव",
    contact_number: "9876543212",
    job_type: "full-time",
  },
  {
    title_hindi: "दुकान पर असिस्टेंट चाहिए",
    title_english: "Shop Assistant Required",
    company_name: "Gupta General Store",
    location_area: "Aminabad",
    category: "shop-assistant",
    salary_min: 7000,
    salary_max: 10000,
    salary_text_hindi: "₹7,000 - ₹10,000 प्रति महीना",
    description_hindi: "अमीनाबाद में किराना दुकान पर असिस्टेंट चाहिए। दुकान पर आने वाले ग्राहकों की मदद करनी होगी। गिनती और हिसाब का ज्ञान होना चाहिए।",
    qualification: "8वीं पास",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543213",
    job_type: "full-time",
  },
  {
    title_hindi: "होम ट्यूशन टीचर चाहिए",
    title_english: "Home Tuition Teacher Required",
    company_name: "Verma Academy",
    location_area: "Aliganj",
    category: "teaching",
    salary_min: 5000,
    salary_max: 10000,
    salary_text_hindi: "₹5,000 - ₹10,000 प्रति महीना",
    description_hindi: "अलीगंज में कक्षा 1-8 के बच्चों को पढ़ाने के लिए ट्यूशन टीचर चाहिए। सभी विषय पढ़ाने होंगे। धैर्य और बच्चों से प्यार होना चाहिए।",
    qualification: "ग्रेजुएशन",
    experience: "1 साल का अनुभव",
    contact_number: "9876543214",
    job_type: "part-time",
  },
  {
    title_hindi: "घर से काम करें - टाइपिंग जॉब",
    title_english: "Work From Home Typing Job",
    company_name: "Digital Solutions",
    location_area: "Vikas Nagar",
    category: "work-from-home",
    salary_min: 6000,
    salary_max: 12000,
    salary_text_hindi: "₹6,000 - ₹12,000 प्रति महीना",
    description_hindi: "घर से काम करने का मौका। टाइपिंग का काम है। आपको दिए गए डॉक्यूमेंट को टाइप करना होगा। लैपटॉप या कंप्यूटर होना जरूरी है।",
    qualification: "10वीं पास, टाइपिंग का ज्ञान",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543215",
    job_type: "work-from-home",
  },
  {
    title_hindi: "सिक्योरिटी गार्ड चाहिए",
    title_english: "Security Guard Required",
    company_name: "SafeGuard Security",
    location_area: "Mahanagar",
    category: "technical",
    salary_min: 8000,
    salary_max: 10000,
    salary_text_hindi: "₹8,000 - ₹10,000 प्रति महीना",
    description_hindi: "महानगर में एक कमर्शियल बिल्डिंग के लिए सिक्योरिटी गार्ड चाहिए। नाइट शिफ्ट में काम करना होगा। फिजिकली फिट होना जरूरी है।",
    qualification: "10वीं पास",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543216",
    job_type: "full-time",
  },
  {
    title_hindi: "होटल में कुक/शेफ चाहिए",
    title_english: "Cook/Chef Required in Hotel",
    company_name: "Royal Palace Hotel",
    location_area: "Charbagh",
    category: "hotel-restaurant",
    salary_min: 10000,
    salary_max: 18000,
    salary_text_hindi: "₹10,000 - ₹18,000 प्रति महीना",
    description_hindi: "चारबाग स्थित होटल में कुक/शेफ चाहिए। उत्तर भारतीय और दक्षिण भारतीय व्यंजन बनाने का अनुभव होना चाहिए। सुबह 7 बजे से शाम 5 बजे तक ड्यूटी।",
    qualification: "10वीं पास, कुकिंग का अनुभव",
    experience: "2 साल का अनुभव",
    contact_number: "9876543217",
    job_type: "full-time",
  },
  {
    title_hindi: "सेल्स मैनेजर चाहिए",
    title_english: "Sales Manager Required",
    company_name: "Bajaj Electronics",
    location_area: "Rajajipuram",
    category: "sales",
    salary_min: 15000,
    salary_max: 25000,
    salary_text_hindi: "₹15,000 - ₹25,000 प्रति महीना",
    description_hindi: "राजाजीपुरम शोरूम के लिए सेल्स मैनेजर चाहिए। ग्राहकों को प्रोडक्ट के बारे में बताना और सेल्स करनी होगी। अच्छी कम्युनिकेशन स्किल चाहिए।",
    qualification: "ग्रेजुएशन",
    experience: "1 साल का अनुभव",
    contact_number: "9876543218",
    job_type: "full-time",
  },
  {
    title_hindi: "मेडिकल स्टोर पर असिस्टेंट",
    title_english: "Medical Store Assistant",
    company_name: "Aarogya Medical Store",
    location_area: "Alambagh",
    category: "medical",
    salary_min: 8000,
    salary_max: 12000,
    salary_text_hindi: "₹8,000 - ₹12,000 प्रति महीना",
    description_hindi: "आलमबाग में मेडिकल स्टोर पर असिस्टेंट चाहिए। दवाइयों की जानकारी होनी चाहिए। D.Pharm या B.Pharm करने वालों को प्राथमिकता दी जाएगी।",
    qualification: "D.Pharm / B.Pharm",
    experience: "1 साल का अनुभव",
    contact_number: "9876543219",
    job_type: "full-time",
  },
  {
    title_hindi: "कंप्यूटर ऑपरेटर चाहिए",
    title_english: "Computer Operator Required",
    company_name: "Innovative IT Solutions",
    location_area: "Kaiserbagh",
    category: "computer",
    salary_min: 10000,
    salary_max: 15000,
    salary_text_hindi: "₹10,000 - ₹15,000 प्रति महीना",
    description_hindi: "कैसरबाग में कंप्यूटर ऑपरेटर चाहिए। MS Excel, Word, और इंटरनेट की अच्छी नॉलेज होनी चाहिए। डेटा एंट्री और डॉक्यूमेंटेशन का काम होगा।",
    qualification: "12वीं पास, कंप्यूटर कोर्स",
    experience: "6 महीने का अनुभव",
    contact_number: "9876543220",
    job_type: "full-time",
  },
  {
    title_hindi: "कंस्ट्रक्शन वर्कर चाहिए",
    title_english: "Construction Worker Required",
    company_name: "Sharma Construction",
    location_area: "Sitapur Road",
    category: "construction",
    salary_min: 12000,
    salary_max: 18000,
    salary_text_hindi: "₹12,000 - ₹18,000 प्रति महीना",
    description_hindi: "सीतापुर रोड पर कंस्ट्रक्शन साइट के लिए मजदूर चाहिए। फिजिकल वर्क करना होगा। रोजाना मजदूरी दी जाएगी। सुबह 8 बजे से शाम 6 बजे तक काम।",
    qualification: "फिजिकली फिट",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543221",
    job_type: "full-time",
  },
  {
    title_hindi: "स्विगी डिलीवरी पार्टनर",
    title_english: "Swiggy Delivery Partner",
    company_name: "Swiggy",
    location_area: "Chinhat",
    category: "delivery",
    salary_min: 10000,
    salary_max: 20000,
    salary_text_hindi: "₹10,000 - ₹20,000 प्रति महीना",
    description_hindi: "स्विगी के लिए डिलीवरी पार्टनर चाहिए। अपना स्मार्टफोन और बाइक होना जरूरी है। फ्लेक्सिबल टाइमिंग। अच्छी कमाई का मौका।",
    qualification: "10वीं पास, स्मार्टफोन",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543222",
    job_type: "full-time",
  },
  {
    title_hindi: "ब्यूटी पार्लर में कर्मचारी",
    title_english: "Beauty Parlor Staff Required",
    company_name: "Glow Beauty Parlor",
    location_area: "Faizabad Road",
    category: "hotel-restaurant",
    salary_min: 6000,
    salary_max: 10000,
    salary_text_hindi: "₹6,000 - ₹10,000 प्रति महीना",
    description_hindi: "फैजाबाद रोड पर ब्यूटी पार्लर में महिला कर्मचारी चाहिए। मेंडी, थ्रेडिंग और बेसिक ब्यूटी सर्विस का अनुभव होना चाहिए।",
    qualification: "10वीं पास, ब्यूटी कोर्स",
    experience: "1 साल का अनुभव",
    contact_number: "9876543223",
    job_type: "full-time",
  },
  {
    title_hindi: "पार्ट टाइम डेटा एंट्री - घर से",
    title_english: "Part Time Data Entry From Home",
    company_name: "HomeWork Solutions",
    location_area: "Gomti Nagar",
    category: "data-entry",
    salary_min: 4000,
    salary_max: 8000,
    salary_text_hindi: "₹4,000 - ₹8,000 प्रति महीना",
    description_hindi: "पार्ट टाइम डेटा एंट्री का काम घर से करें। रोजाना 3-4 घंटे काम करना होगा। मोबाइल या कंप्यूटर से काम कर सकते हैं।",
    qualification: "10वीं पास",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543224",
    job_type: "part-time",
  },
  {
    title_hindi: "Tele-caller चाहिए",
    title_english: "Tele-caller Required",
    company_name: "Connect BPO",
    location_area: "Hazratganj",
    category: "sales",
    salary_min: 8000,
    salary_max: 12000,
    salary_text_hindi: "₹8,000 - ₹12,000 प्रति महीना",
    description_hindi: "हजरतगंज में Tele-caller चाहिए। ग्राहकों को कॉल करके प्रोडक्ट के बारे में बताना होगा। अच्छी बोलने की क्षमता होनी चाहिए। हिंदी में बातचीत करनी है।",
    qualification: "12वीं पास",
    experience: "6 महीने का अनुभव",
    contact_number: "9876543225",
    job_type: "full-time",
  },
  {
    title_hindi: "टेलर/सिलाई मास्टर चाहिए",
    title_english: "Tailor/Sewing Master Required",
    company_name: "Fashion Tailors",
    location_area: "Aminabad",
    category: "technical",
    salary_min: 10000,
    salary_max: 15000,
    salary_text_hindi: "₹10,000 - ₹15,000 प्रति महीना",
    description_hindi: "अमीनाबाद में टेलर/सिलाई मास्टर चाहिए। पुरुष और महिला दोनों अप्लाई कर सकते हैं। सिलाई की अच्छी नॉलेज होनी चाहिए। नई डिजाइन सीखने की इच्छा हो।",
    qualification: "सिलाई का ज्ञान",
    experience: "2 साल का अनुभव",
    contact_number: "9876543226",
    job_type: "full-time",
  },
  {
    title_hindi: "फील्ड वर्कर चाहिए (एनजीओ)",
    title_english: "NGO Field Worker Required",
    company_name: "Seva Foundation",
    location_area: "Sultanpur Road",
    category: "sales",
    salary_min: 8000,
    salary_max: 12000,
    salary_text_hindi: "₹8,000 - ₹12,000 प्रति महीना",
    description_hindi: "एनजीओ के लिए फील्ड वर्कर चाहिए। लखनऊ के विभिन्न इलाकों में जाकर सर्वे करना होगा। सामाजिक कार्यों में रुचि होनी चाहिए।",
    qualification: "ग्रेजुएशन",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543227",
    job_type: "full-time",
  },
  {
    title_hindi: "बेकरी में स्टाफ चाहिए",
    title_english: "Bakery Staff Required",
    company_name: "Fresh Bakes Bakery",
    location_area: "Kanpur Road",
    category: "hotel-restaurant",
    salary_min: 7000,
    salary_max: 10000,
    salary_text_hindi: "₹7,000 - ₹10,000 प्रति महीना",
    description_hindi: "कानपुर रोड पर बेकरी में स्टाफ चाहिए। बेकरी प्रोडक्ट बनाने और सर्व करने में मदद करनी होगी। साफ-सफाई का ध्यान रखना होगा।",
    qualification: "10वीं पास",
    experience: "कोई अनुभव नहीं चाहिए",
    contact_number: "9876543228",
    job_type: "full-time",
  },
  {
    title_hindi: "ऑनलाइन टीचर चाहिए (घर से)",
    title_english: "Online Teacher Required (From Home)",
    company_name: "EduTech Online",
    location_area: "Aliganj",
    category: "teaching",
    salary_min: 5000,
    salary_max: 15000,
    salary_text_hindi: "₹5,000 - ₹15,000 प्रति महीना",
    description_hindi: "घर से ऑनलाइन पढ़ाने के लिए टीचर चाहिए। कक्षा 1-10 तक के बच्चों को ऑनलाइन पढ़ाना होगा। लैपटॉप और अच्छा इंटरनेट कनेक्शन होना चाहिए।",
    qualification: "ग्रेजुएशन, B.Ed प्राथमिकता",
    experience: "1 साल का अनुभव",
    contact_number: "9876543229",
    job_type: "work-from-home",
  },
];

async function seed() {
  console.log("Starting seed...");
  console.log(`Will insert ${sampleJobs.length} jobs`);

  for (const job of sampleJobs) {
    const slug = generateSlug(job.title_hindi) + "-" + job.location_area.toLowerCase().replace(/\s+/g, "-") + "-lucknow";

    const { error } = await supabase.from("jobs").insert({
      ...job,
      slug,
      apply_link: "",
      is_featured: false,
      is_active: true,
      is_paid: false,
      source: "manual",
      posted_at: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
      expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      views: Math.floor(Math.random() * 500),
    });

    if (error) {
      console.error(`Error inserting ${job.title_hindi}:`, error.message);
    } else {
      console.log(`✓ ${job.title_hindi}`);
    }
  }

  console.log("Seed complete!");
}

seed().catch(console.error);
